# These substitutions allow the end user to override certain values
substitutions:
  name: "arlec-ald095ha"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: arlec-ald095ha
    version: "1.0"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://ajhutton/esp-config/arlec-ald095ha.yaml@main

libretuya:
  board: wb2s
  framework:
    version: dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "$devicename-fallback"

captive_portal:

web_server:
  local: true

#pwm 4 (P24) D6 is clock, pwm5 (P26) D7 is data
sm2135:
  data_pin: GPIO26
  clock_pin: GPIO24
  cw_current: 20mA

# Individual outputsmap command 1 2 0 4 3
output:
  - platform: sm2135
    id: output_green
    channel: 1
  - platform: sm2135
    id: output_blue
    channel: 0
  - platform: sm2135
    id: output_red
    channel: 2
  - platform: sm2135
    id: output_white
    channel: 4
  - platform: sm2135
    id: output_warmwhite
    channel: 3
    #fix up above max

light:
  - platform: rgbww
    name: "Downlight"
    red: output_red
    green: output_green
    blue: output_blue
    color_interlock: true
    cold_white: output_white
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 3000 K

    effects:
      - random:

sensor:
  - platform: wifi_signal
    name: "WiFi"
    update_interval: 60s
